DROP TABLE GCG_4041_NCMR_DSPLOG;
CREATE TABLE GCG_NCMR_DISP_LOG(
CONTROL_NUMBER CHAR(7),
DISPOSITION_SEQ CHAR(3),
DATE_DISPOSED DATE,
FLAG_INTERNAL_ONLY CHAR(1),
DISPOSITION_BY CHAR(50),
AREA CHAR(50),
REJECTION_POINT CHAR(50));